Sujata Added An API to create new event.
kaurgurpal/Eventbrite pull request #12
Opened 2019-09-20 06:35 UTC by sstambat12

2019-09-20 17:41 UTC, LeelaCreations requested changes

2019-09-20 17:41 UTC, LeelaCreations commented on EventCatalog/Controllers/CatalogController.cs
> +        public async Task<ActionResult<EventsCatalog>> CreateEvent(EventsCatalog eventsCatalog)
Seems @kaurgurpal  has handled exceptions as well. can you check her PR once..

2019-09-21 04:44 UTC, LeelaCreations approved these changes
looks good to me

2019-09-21 16:43 UTC, kaurgurpal approved these changes
Ok

2019-09-21 16:44 UTC, merged